--THIS QUERY RETURNS A COUNT OF UNIQUE SUBJECT IDS NOTES WHERE 
--DISCHARGE SUMMARY TEXT CONTAINS "GRAND MAL"

SELECT COUNT(DISTINCT "SUBJECT_ID") AS "TOTAL_PATIENTS" FROM "MIMIC2V26"."noteevents" 
	WHERE text LIKE '%grand mal%'

--THIS QUERY RETURNS ALL NOTES WHERE TEXT CONTAINS "GRAND MAL"
SELECT *
FROM "MIMIC2V26"."noteevents" 
WHERE "CATEGORY" 
LIKE '%DISCHARGE%' AND text LIKE '%grand mal%'